properties
storePassword=diublooddonorly
keyPassword=diublooddonorly
keyAlias=upload
storeFile=../release_key/upload.jks


#properties
#storePassword=hilfulfuzul
#keyPassword=hilfulfuzul
#keyAlias=upload
#storeFile=../release_key/upload-keystore.jks